// Auto-generated by scripts/build-inset-geojson.mjs — do not edit by hand
export type InsetTransform = { srcCenter: [number, number]; tgtCenter: [number, number]; scale: number; yScale?: number };

export const INSET_TRANSFORMS: Record<string, InsetTransform> = {
  "AK": {
    "srcCenter": [
      -153.5,
      63.5
    ],
    "tgtCenter": [
      -118.5,
      25.5
    ],
    "scale": 0.29,
    "yScale": 0.587
  },
  "HI": {
    "srcCenter": [
      -157.5,
      20.5
    ],
    "tgtCenter": [
      -108.5,
      24.5
    ],
    "scale": 0.8
  },
  "GU": {
    "srcCenter": [
      144.79,
      13.45
    ],
    "tgtCenter": [
      -104.8,
      24.5
    ],
    "scale": 1
  },
  "MP": {
    "srcCenter": [
      145.6,
      16.5
    ],
    "tgtCenter": [
      -103.2,
      25.5
    ],
    "scale": 1
  },
  "AS": {
    "srcCenter": [
      -170.13,
      -14.3
    ],
    "tgtCenter": [
      -101.5,
      24.5
    ],
    "scale": 1
  },
  "PR": {
    "srcCenter": [
      -66.59,
      18.22
    ],
    "tgtCenter": [
      -99.5,
      24.5
    ],
    "scale": 1
  },
  "VI": {
    "srcCenter": [
      -64.83,
      18.03
    ],
    "tgtCenter": [
      -97.5,
      24.5
    ],
    "scale": 1
  }
};

/** Returns inset-mapped lng/lat for display on the map, or real coords if no transform is needed. */
export function toInsetCoords(lng: number, lat: number, stateAbbr: string): [number, number] {
  const t = INSET_TRANSFORMS[stateAbbr];
  if (!t) return [lng, lat];
  const normLng = lng > 170 ? lng - 360 : lng;
  return [
    t.tgtCenter[0] + t.scale * (normLng - t.srcCenter[0]),
    t.tgtCenter[1] + (t.yScale ?? t.scale) * (lat - t.srcCenter[1]),
  ];
}
