export type GlossaryTerm = {
  term: string;
  definition: string;
  seeAlso?: string[];
  learnMoreHref?: string;
};

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    term: "287(g)",
    definition:
      "Section 287(g) of the Immigration and Nationality Act authorizes the Department of Homeland Security to enter into agreements with state and local law enforcement agencies, granting local officers the power to enforce federal immigration law.",
    seeAlso: ["Memorandum of Agreement", "ICE"],
  },
  {
    term: "Administrative warrant",
    definition:
      "A civil warrant issued by an immigration officer rather than a federal judge — typically Form I-200 (warrant of arrest) or I-205 (warrant of removal). Unlike criminal warrants, administrative warrants don't authorize entry into a private home — but they do let 287(g) officers, especially under the Warrant Service Officer model, detain named individuals for ICE pickup.",
    seeAlso: ["Detainer", "Warrant Service Officer"],
  },
  {
    term: "Alien Registration Number",
    definition:
      "A unique seven-, eight-, or nine-digit identifier — also called an A-Number — that DHS assigns to a noncitizen, usually the first time they're processed for an immigration benefit or enforcement action. It stays with a person for life and links every record in their file, including anything generated by a 287(g) encounter, in the Central Index System.",
    seeAlso: ["Central Index System", "Notice to Appear"],
  },
  {
    term: "Central Index System",
    definition:
      "USCIS's master database indexing every noncitizen's immigration file by Alien Registration Number, tracking status, applications, and enforcement encounters as a person moves through the immigration system. It's one of the databases a 287(g) officer checks when screening someone in custody.",
    seeAlso: ["Alien Registration Number"],
  },
  {
    term: "Civil immigration violation",
    definition:
      "Being present in the United States without authorization is a civil violation, not a criminal one. This distinction matters for what local officers can legally do under 287(g).",
    seeAlso: ["287(g)", "Detainer"],
  },
  {
    term: "Designated Immigration Officer",
    definition:
      "The formal ICE designation — abbreviated DIO — for a local officer authorized to perform immigration enforcement functions under a 287(g) agreement. Candidates are nominated by their agency, background-checked and trained by ICE, and must pass certification before ICE issues them official credentials (ICE Form 70-006) and a signed authorization letter. Only certified DIOs may act under the MOA, and their authority can be revoked at any time.",
    seeAlso: ["Memorandum of Agreement", "Field Office Director", "Supervisory Immigration Enforcement Agent"],
  },
  {
    term: "Detainer",
    definition:
      "A request from ICE asking a local jail to hold a person — typically up to 48 hours past their scheduled release — so ICE can take custody. Federal courts have found that complying with a detainer without an independent legal basis can violate the Fourth Amendment, and a number of jurisdictions decline them for that reason.",
    seeAlso: ["Jail Enforcement Model", "Civil immigration violation", "Fourth Amendment"],
  },
  {
    term: "Eligible agencies",
    definition:
      "Section 287(g) authorizes agreements with \"a State, or any political subdivision of a State\" — in practice, any state or local law enforcement agency, from a county sheriff's office to a state corrections department. There's no published checklist beyond that; ICE has sole discretion over which applications it accepts and how it manages its resources.",
    seeAlso: ["287(g)", "Memorandum of Agreement"],
  },
  {
    term: "Enforcement and Removal Operations",
    definition:
      "ICE's largest division — abbreviated ERO — responsible for arresting, detaining, and deporting noncitizens, and the office that administers the 287(g) program day to day. Field Office Directors report up through ERO; a serious violation of an MOA can be escalated to ERO's Executive Associate Director, who can recommend suspending the agreement.",
    seeAlso: ["ICE", "Field Office Director"],
  },
  {
    term: "Expedited removal",
    definition:
      "A fast-track deportation process that lets ICE remove certain noncitizens without a hearing before an immigration judge. It covers a narrower set of cases than ordinary removal proceedings, but its scope has expanded significantly over the years.",
    seeAlso: ["Removal", "Immigration judge", "Notice to Appear"],
  },
  {
    term: "Federal Law Enforcement Training Center",
    definition:
      "The federal government's primary law enforcement training facility, based in Glynco, Georgia — abbreviated FLETC. It's where 287(g) officers under the Jail Enforcement Model, and Task Force Model officers before that program was shut down in 2012, complete their initial certification course.",
    seeAlso: ["Jail Enforcement Model", "Task Force Model", "Designated Immigration Officer"],
  },
  {
    term: "Field office",
    definition:
      "One of ICE's regional administrative offices, each overseeing 287(g) agreements and other enforcement activity across a multi-state territory. A local agency's MOA is signed with, and reports up through, a specific field office.",
    seeAlso: ["ICE", "Memorandum of Agreement", "Field Office Director"],
  },
  {
    term: "Field Office Director",
    definition:
      "The ICE official — abbreviated FOD — who leads a field office's operations, including every 287(g) agreement in its territory. The FOD signs each participating officer's authorization letter, provides ICE's point of contact under the MOA, and can revoke an officer's delegated authority at any time.",
    seeAlso: ["Field office", "Enforcement and Removal Operations", "Designated Immigration Officer"],
  },
  {
    term: "Fourth Amendment",
    definition:
      "The constitutional protection against unreasonable searches and seizures. It's the legal basis for most challenges to 287(g) practices — including holding someone on a detainer alone, without a judicial warrant or independent probable cause — and for concerns about pretextual arrests used to funnel people into immigration screening.",
    seeAlso: ["Detainer", "Pretextual arrest"],
  },
  {
    term: "ICE",
    definition:
      "U.S. Immigration and Customs Enforcement, the federal agency within the Department of Homeland Security responsible for civil immigration enforcement.",
    seeAlso: ["287(g)", "Enforcement and Removal Operations"],
  },
  {
    term: "Immigration and Nationality Act",
    definition:
      "The primary federal statute governing immigration to the United States, originally passed in 1952 and amended many times since — abbreviated INA. Section 287(g), the specific provision this program is named for, was added in 1996 and gives DHS the authority to delegate immigration enforcement functions to state and local agencies.",
    seeAlso: ["287(g)", "ICE"],
  },
  {
    term: "Immigration judge",
    definition:
      "An administrative judge within the Department of Justice's Executive Office for Immigration Review — not part of the regular federal court system — who presides over removal proceedings. Not everyone facing removal appears before one: expedited removal and other fast-track processes bypass a hearing entirely in many cases.",
    seeAlso: ["Removal", "Expedited removal", "Notice to Appear"],
  },
  {
    term: "Jail Enforcement Model",
    definition:
      "The most common 287(g) model. Trained local officers screen people booked into the jail, run them against immigration databases, and flag those who may be removable so ICE can lodge a detainer. Activity is confined to the jail — no community arrests.",
    seeAlso: ["287(g)", "Task Force Model", "Warrant Service Officer"],
    learnMoreHref: "/model/jail",
  },
  {
    term: "Memorandum of Agreement",
    definition:
      "The formal contract between ICE and a local law enforcement agency that establishes the terms of a 287(g) partnership, specifying which officers are trained, what authority they have, and oversight requirements.",
    seeAlso: ["287(g)", "Eligible agencies", "Steering Committee"],
  },
  {
    term: "MOA",
    definition: "Short for Memorandum of Agreement — the formal contract between ICE and a local agency.",
    seeAlso: ["Memorandum of Agreement"],
  },
  {
    term: "Notice to Appear",
    definition:
      "The charging document — Form I-862, abbreviated NTA — that formally starts removal proceedings, listing the government's allegations, the grounds for removal, and the immigration court date. Receiving an NTA doesn't mean someone will be deported; it means their case is now in front of an immigration judge, who they have the right to appear before and contest it.",
    seeAlso: ["Immigration judge", "Removal", "Alien Registration Number"],
  },
  {
    term: "Pretextual arrest",
    definition:
      "Using a minor, often unrelated offense — a broken taillight, a traffic stop — as the occasion to arrest someone, book them into jail, and trigger the immigration screening that follows. Civil rights groups and federal investigators have repeatedly flagged this as a way 287(g) authority ends up targeting people based on how they look or sound rather than what they did.",
    seeAlso: ["Task Force Model", "Fourth Amendment"],
  },
  {
    term: "Sanctuary jurisdiction",
    definition:
      "A state or locality with a law or policy that limits local cooperation with federal immigration enforcement — commonly by restricting how long a jail can hold someone on an ICE detainer alone. Sanctuary status varies by degree and by jurisdiction; it doesn't necessarily mean zero cooperation, and some states with such laws still have local agencies signed onto 287(g) through models the law doesn't restrict.",
    seeAlso: ["Detainer", "287(g)"],
  },
  {
    term: "Removal",
    definition:
      "The official term for being deported. Removal happens either through an immigration judge's order or — far more often — through expedited procedures that bypass the courts entirely. ICE carries out the physical removal.",
    seeAlso: ["ICE", "Detainer", "Expedited removal", "Immigration judge", "Notice to Appear"],
  },
  {
    term: "Steering Committee",
    definition:
      "A local oversight body some 287(g) agreements call for, meant to include community stakeholders and give the public a channel to weigh in on how the agreement is working. In practice, compliance has been inconsistent — reviews of active agreements have repeatedly found that most jurisdictions haven't held a public steering committee meeting or kept any public record of one.",
    seeAlso: ["Memorandum of Agreement"],
  },
  {
    term: "Supervisory Immigration Enforcement Agent",
    definition:
      "The ICE officer responsible for overseeing a group of Designated Immigration Officers' casework under an MOA — reviewing their actions, signing off on steps like detainers, and serving as the ICE-side point of contact for day-to-day questions in the field.",
    seeAlso: ["Designated Immigration Officer", "Field Office Director"],
  },
  {
    term: "Task Force Model",
    definition:
      "The broadest 287(g) authority. Trained local officers ride along with ICE field agents to stop, question, and arrest people for immigration violations in the community — not just those already in custody.",
    seeAlso: ["287(g)", "Jail Enforcement Model", "Warrant Service Officer", "Pretextual arrest"],
    learnMoreHref: "/model/taskforce",
  },
  {
    term: "Warrant Service Officer",
    definition:
      "The narrowest 287(g) model. Local officers — typically in a jail setting — execute ICE administrative warrants on people ICE has already named. They can't decide who's targeted and can't make independent immigration arrests.",
    seeAlso: ["287(g)", "Administrative warrant", "Jail Enforcement Model"],
    learnMoreHref: "/model/wso",
  },
];

export const TERMS_MAP = new Map(
  GLOSSARY_TERMS.map((t) => [t.term.toLowerCase(), t])
);

export function termSlug(term: string): string {
  return term.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}
